version: '3.5'
services:
  postgres10:
    image: postgres:10
    environment:
      POSTGRES_USER: ${PGUSER:-foo}
      POSTGRES_PASSWORD: ${PGPASSWORD:-foo}
      POSTGRES_DB: ${PGPGDATABASE:-foo}
    ports:
      - "22410:5432"
  postgres11:
    container_name: 'postgres11'
    image: postgres:11
    environment:
      POSTGRES_USER: ${PGUSER:-foo}
      POSTGRES_PASSWORD: ${PGPASSWORD:-foo}
      POSTGRES_DB: ${PGPGDATABASE:-foo}
    ports:
      - "22411:5432"
  postgres12:
    image: postgres:12
    container_name: 'postgres12'
    environment:
      POSTGRES_USER: ${PGUSER:-foo}
      POSTGRES_PASSWORD: ${PGPASSWORD:-foo}
      POSTGRES_DB: ${PGPGDATABASE:-foo}
    ports:
      - "22412:5432"
  postgres13:
    container_name: 'postgres13'
    image: ginden/postgres-plv8:13
    environment:
      POSTGRES_USER: ${PGUSER:-foo}
      POSTGRES_PASSWORD: ${PGPASSWORD:-foo}
      POSTGRES_DB: ${PGPGDATABASE:-foo}
    ports:
      - "22413:5432"
